apiVersion: v1
kind: ConfigMap
metadata:
  name: yieldrails-config
  namespace: yieldrails-prod
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  API_VERSION: "v1"
  CORS_ORIGIN: "https://app.yieldrails.com"
  RATE_LIMIT_WINDOW: "900000"
  RATE_LIMIT_MAX: "100"
  JWT_EXPIRY: "1h"
  JWT_REFRESH_EXPIRY: "7d"
  SESSION_MAX_AGE: "86400000"
  BCRYPT_ROUNDS: "12"
  MAX_FILE_SIZE: "10485760"
  PAGINATION_DEFAULT_LIMIT: "20"
  PAGINATION_MAX_LIMIT: "100"
  
  # Database Configuration
  DB_POOL_MIN: "2"
  DB_POOL_MAX: "10"
  DB_TIMEOUT: "20000"
  
  # Redis Configuration
  REDIS_KEY_PREFIX: "yieldrails:"
  REDIS_DEFAULT_TTL: "3600"
  
  # External Service URLs
  CHAINALYSIS_API_URL: "https://api.chainalysis.com"
  CIRCLE_API_URL: "https://api.circle.com"
  MOONPAY_API_URL: "https://api.moonpay.com"
  
  # Blockchain Configuration
  ETHEREUM_NETWORK: "mainnet"
  POLYGON_NETWORK: "mainnet"
  ARBITRUM_NETWORK: "mainnet"
  BASE_NETWORK: "mainnet"
  
  # Monitoring Configuration
  METRICS_PORT: "9090"
  HEALTH_CHECK_PORT: "8080"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yieldrails-staging-config
  namespace: yieldrails-staging
data:
  NODE_ENV: "staging"
  LOG_LEVEL: "debug"
  API_VERSION: "v1"
  CORS_ORIGIN: "https://staging.yieldrails.com"
  RATE_LIMIT_WINDOW: "900000"
  RATE_LIMIT_MAX: "200"
  JWT_EXPIRY: "1h"
  JWT_REFRESH_EXPIRY: "7d"
  SESSION_MAX_AGE: "86400000"
  BCRYPT_ROUNDS: "10"
  MAX_FILE_SIZE: "10485760"
  PAGINATION_DEFAULT_LIMIT: "20"
  PAGINATION_MAX_LIMIT: "100"
  
  # Database Configuration
  DB_POOL_MIN: "1"
  DB_POOL_MAX: "5"
  DB_TIMEOUT: "20000"
  
  # Redis Configuration
  REDIS_KEY_PREFIX: "yieldrails:staging:"
  REDIS_DEFAULT_TTL: "1800"
  
  # External Service URLs
  CHAINALYSIS_API_URL: "https://api.chainalysis.com"
  CIRCLE_API_URL: "https://api-sandbox.circle.com"
  MOONPAY_API_URL: "https://api.moonpay.com"
  
  # Blockchain Configuration (Testnets)
  ETHEREUM_NETWORK: "sepolia"
  POLYGON_NETWORK: "mumbai"
  ARBITRUM_NETWORK: "arbitrum-sepolia"
  BASE_NETWORK: "base-sepolia"
  
  # Monitoring Configuration
  METRICS_PORT: "9090"
  HEALTH_CHECK_PORT: "8080"